run_type = "transfer_learning"
device = "cpu"
tb_logdir = "reinvent_integration/results/tb_transfer_series_ce"

[parameters]
num_epochs = 8
save_every_n_epochs = 2
batch_size = 64
sample_batch_size = 256
num_refs = 5

input_model_file = "reinvent_integration/results/series_ce_seed_prior.model"
output_model_file = "reinvent_integration/results/series_ce_tuned_reinvent.model"
smiles_file = "reinvent_integration/data/series_ce_unique.smi"
validation_smiles_file = "reinvent_integration/data/series_ce_unique.smi"

standardize_smiles = true
randomize_smiles = true
randomize_all_smiles = false
internal_diversity = true
