run_type = "sampling"
device = "cpu"

[parameters]
model_file = "reinvent_integration/results/linkinvent_cl_adme/linkinvent_cl_stage2.chkpt"
smiles_file = "reinvent_integration/data/warheads.smi"
output_file = "reinvent_integration/results/linkinvent_cl/samples.csv"
num_smiles = 500
unique_molecules = false
randomize_smiles = true
