run_type = "sampling"
device = "cuda"

[parameters]
model_file = "reinvent_integration/results/mol2mol_rl_adme/mol2mol_rl_adme.chkpt"
smiles_file = "reinvent_integration/data/series_ce_unique.smi"
sample_strategy = "multinomial"
temperature = 1.0
output_file = "reinvent_integration/results/mol2mol_rl_adme/samples.csv"
num_smiles = 150
unique_molecules = false
randomize_smiles = false
