## Sampling from correctly fine-tuned Series C/E model (from reinvent.prior)
run_type = "sampling"
device = "cpu"

[parameters]
model_file = "reinvent_integration/results/series_ce_finetune_correct.model"
num_smiles = 5000
output_file = "reinvent_integration/results/finetuned_raw_samples.csv"
unique_molecules = false
randomize_smiles = true
