run_type = "sampling"
device = "cpu"

[parameters]
model_file = "reinvent_integration/results/reinvent_cl_adme/reinvent_cl_stage2.chkpt"
output_file = "reinvent_integration/results/reinvent_cl/samples.csv"
num_smiles = 2000
unique_molecules = false
randomize_smiles = true
