run_type = "sampling"
device = "cuda"
[parameters]
model_file = "reinvent_integration/priors/reinvent.prior"
output_file = "reinvent_integration/results/reinvent_plain/samples.csv"
num_smiles = 1
unique_molecules = false
randomize_smiles = true
