run_type = "sampling"
device = "cuda"
[parameters]
model_file = "reinvent_integration/priors/mol2mol_mmp.prior"
smiles_file = "reinvent_integration/data/nitro_leads.smi"
sample_strategy = "beamsearch"
temperature = 1.0
output_file = "reinvent_integration/results/mol2mol_mmp_plain/samples.csv"
num_smiles = 2000
unique_molecules = false
randomize_smiles = true
