run_type = "sampling"
device = "cuda"
[parameters]
model_file = "reinvent_integration/results/linkinvent_transformer_pubchem_rl_adme/linkinvent_transformer_pubchem_rl.chkpt"
smiles_file = "reinvent_integration/data/warheads.smi"
output_file = "reinvent_integration/results/linkinvent_transformer_pubchem_rl/samples.csv"
num_smiles = 2000
unique_molecules = false
randomize_smiles = true
