run_type = "sampling"
device = "cuda"
[parameters]
model_file = "reinvent_integration/results/mol2mol_scaffold_generic_rl_adme/mol2mol_scaffold_generic_rl.chkpt"
smiles_file = "reinvent_integration/data/series_ce_unique.smi"
sample_strategy = "beamsearch"
temperature = 1.0
output_file = "reinvent_integration/results/mol2mol_scaffold_generic_rl/samples.csv"
num_smiles = 2000
unique_molecules = false
randomize_smiles = true
